image:
  repository: k8s.gcr.io/external-dns/external-dns
  tag: "v0.10.1"

serviceAccount:
  create: true

podSecurityContext:
  fsGroup: 65534

securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

policy: sync

provider: aws